export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';

export const FETCH_CONFIG_START = 'FETCH_CONFIG_START'
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS'
export const FETCH_CONFIG_FAIL = 'FETCH_CONFIG_FAIL'

export const UPDATE_CONFIG_START = 'UPDATE_CONFIG_START'
export const UPDATE_CONFIG_SUCCESS = 'UPDATE_CONFIG_SUCCESS'
export const UPDATE_CONFIG_FAIL = 'UPDATE_CONFIG_FAIL'

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const CHECK_USER_SESSION = 'CHECK_USER_SESSION';

export const CREATE_ACCOUNT_START = 'CREATE_ACCOUNT_START';
export const CREATE_ACCOUNT_FAIL = 'CREATE_ACCOUNT_FAIL';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';

export const UPDATE_ACCOUNT_START = 'UPDATE_ACCOUNT_START';
export const UPDATE_ACCOUNT_FAIL = 'UPDATE_ACCOUNT_FAIL';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';

export const PASSWORD_RESET_LINK_START = 'PASSWORD_RESET_LINK_START'
export const PASSWORD_RESET_LINK_SUCCESS = 'PASSWORD_RESET_LINK_SUCCESS'
export const PASSWORD_RESET_LINK_FAIL = 'PASSWORD_RESET_LINK_FAIL'

export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'

export const LOGOUT = 'LOGOUT';

export const TOGGLE_FORM = 'TOGGLE_FORM';

export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'

export const SET_SIGNUP_FORM_PAGE = 'SET_SIGNUP_FORM_PAGE'

export const CLEAR_AUTH_NOTIFICATION = 'CLEAR_AUTH_NOTIFICATION'

export const UPDATE_ACTIVITY_START = 'UPDATE_ACTIVITY_START'
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS'
export const UPDATE_ACTIVITY_FAIL = 'UPDATE_ACTIVITY_FAIL'

export const CREATE_UPDATE_COURSE_START = 'CREATE_UPDATE_COURSE_START'
export const CREATE_UPDATE_COURSE_SUCCESS = 'CREATE_UPDATE_COURSE_SUCCESS'
export const CREATE_UPDATE_COURSE_FAIL = 'CREATE_UPDATE_COURSE_FAIL'

export const UPDATE_COURSE_RESOURCES_START = 'UPDATE_COURSE_RESOURCES_START'
export const UPDATE_COURSE_RESOURCES_SUCCESS = 'UPDATE_COURSE_RESOURCES_SUCCESS'
export const UPDATE_COURSE_RESOURCES_FAIL = 'UPDATE_COURSE_RESOURCES_FAIL'

export const DELETE_COURSE_START = 'DELETE_COURSE_START'
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS'
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL'

export const TOGGLE_COURSE_STATE_START = 'TOGGLE_COURSE_STATE_START'
export const TOGGLE_COURSE_STATE_SUCCESS = 'TOGGLE_COURSE_STATE_SUCCESS'
export const TOGGLE_COURSE_STATE_FAIL = 'TOGGLE_COURSE_STATE_FAIL'

export const FETCH_COURSE_START = 'FETCH_COURSE_START'
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS'
export const FETCH_COURSE_FAIL = 'FETCH_COURSE_FAIL'

export const FETCH_LESSON_START = 'FETCH_LESSON_START'
export const FETCH_LESSON_SUCCESS = 'FETCH_LESSON_SUCCESS'
export const FETCH_LESSON_FAIL = 'FETCH_LESSON_FAIL'

export const CREATE_LESSON_START = 'CREATE_LESSON_START'
export const CREATE_LESSON_SUCCESS = 'CREATE_LESSON_SUCCESS'
export const CREATE_LESSON_FAIL = 'CREATE_LESSON_FAIL'

export const DELETE_LESSON_START = 'DELETE_LESSON_START'
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS'
export const DELETE_LESSON_FAIL = 'DELETE_LESSON_FAIL'

export const LOAD_GRADE_TEST_FORM_START = 'LOAD_GRADE_TEST_FORM_START'
export const LOAD_GRADE_TEST_FORM_SUCCESS = 'LOAD_GRADE_TEST_FORM_SUCCESS'
export const LOAD_GRADE_TEST_FORM_FAIL = 'LOAD_GRADE_TEST_FORM_FAIL'

export const GRADE_TEST_START = 'GRADE_TEST_START'
export const GRADE_TEST_SUCCESS = 'GRADE_TEST_SUCCESS'
export const GRADE_TEST_FAIL = 'GRADE_TEST_FAIL'

export const LOAD_TEST_FORM_START = 'LOAD_TEST_FORM_START'
export const LOAD_TEST_FORM_SUCCESS = 'LOAD_TEST_FORM_SUCCESS'
export const LOAD_TEST_FORM_FAIL = 'LOAD_TEST_FORM_FAIL'

export const CREATE_UPDATE_TEST_START = 'CREATE_UPDATE_TEST_START'
export const CREATE_UPDATE_TEST_SUCCESS = 'CREATE_UPDATE_TEST_SUCCESS'
export const CREATE_UPDATE_TEST_FAIL = 'CREATE_UPDATE_TEST_FAIL'

export const DELETE_TEST_START = 'DELETE_TEST_START'
export const DELETE_TEST_SUCCESS = 'DELETE_TEST_SUCCESS'
export const DELETE_TEST_FAIL = 'DELETE_TEST_FAIL'

export const RESET_TEST_START = 'RESET_TEST_START'
export const RESET_TEST_SUCCESS = 'RESET_TEST_SUCCESS'
export const RESET_TEST_FAIL = 'RESET_TEST_FAIL'

export const UNFETCH_INSTRUCTOR_COURSES = 'UNFETCH_INSTRUCTOR_COURSES'

export const SET_COURSE_FORM_PAGE = 'SET_COURSE_FORM_PAGE'
export const SET_CREATE_COURSE_FORM = 'SET_CREATE_COURSE_FORM'
export const SET_CREATE_LESSON_FORM = 'SET_CREATE_LESSON_FORM'

export const FETCH_INSTRUCTORS_START = 'FETCH_INSTRUCTORS_START'
export const FETCH_INSTRUCTORS_SUCCESS = 'FETCH_INSTRUCTORS_SUCCESS'
export const FETCH_INSTRUCTORS_FAIL = 'FETCH_INSTRUCTORS_FAIL'

export const SHOW_COURSE_DETAILS = 'SHOW_COURSE_DETAILS'
export const HIDE_COURSE_DETAILS = 'HIDE_COURSE_DETAILS'

export const FETCH_TEXT_EDITOR_CONTENT = 'FETCH_TEXT_EDITOR_CONTENT'

export const RETURN_TO_COURSES = 'RETURN_TO_COURSES'

export const LOAD_CATEGORY_FORM_DATA = 'LOAD_CATEGORY_FORM_DATA'
export const LOAD_ASSIGNMENT_FORM_DATA = 'LOAD_ASSIGNMENT_FORM_DATA'
export const LOAD_TEST_FORM_DATA = 'LOAD_TEST_FORM_DATA'

export const SELECT_LESSON = 'SELECT_LESSON'
export const SELECT_ASSIGNMENT = 'SELECT_ASSIGNMENT'
export const SELECT_TEST = 'SELECT_TEST'

export const SET_TEST_TO_GRADE = 'SET_TEST_TO_GRADE'
export const CLEAR_TEST_TO_GRADE = 'CLEAR_TEST_TO_GRADE'

export const FORGOT_PASSWORD_PAGE = 'FORGOT_PASSWORD_PAGE'

export const FINISH_EDIT = 'FINISH_EDIT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const CLEAR_INSTRUCTOR_MODAL_STATES = 'CLEAR_INSTRUCTOR_MODAL_STATES'
export const CLEAR_INSTRUCTOR_TAB_CONTENT = 'CLEAR_INSTRUCTOR_TAB_CONTENT'

export const SET_INSTRUCTOR_TAB = 'SET_INSTRUCTOR_TAB'
export const SET_INSTRUCTOR_FOLDER = 'SET_INSTRUCTOR_FOLDER'
export const SET_QUESTION_FORM = 'SET_QUESTION_FORM'
export const SET_QUESTION_EDITING = 'SET_QUESTION_EDITING'
export const SET_QUESTION_DETAIL = 'SET_QUESTION_DETAIL'

export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START'
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS'
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL'

export const FETCH_ALL_STUDENTS_START = 'FETCH_ALL_STUDENTS_START'
export const FETCH_ALL_STUDENTS_SUCCESS = 'FETCH_ALL_STUDENTS_SUCCESS'
export const FETCH_ALL_STUDENTS_FAIL = 'FETCH_ALL_STUDENTS_FAIL'

export const GRADE_COURSE_START = 'GRADE_COURSE_START'
export const GRADE_COURSE_SUCCESS = 'GRADE_COURSE_SUCCESS'
export const GRADE_COURSE_FAIL = 'GRADE_COURSE_FAIL'

export const FETCH_QUESTION_BANK_START = 'FETCH_QUESTION_BANK_START'
export const FETCH_QUESTION_BANK_SUCCESS = 'FETCH_QUESTION_BANK_SUCCESS'
export const FETCH_QUESTION_BANK_FAIL = 'FETCH_QUESTION_BANK_FAIL'

export const CREATE_UPDATE_QUESTION_START = 'CREATE_UPDATE_QUESTION_START'
export const CREATE_UPDATE_QUESTION_SUCCESS = 'CREATE_UPDATE_QUESTION_SUCCESS'
export const CREATE_UPDATE_QUESTION_FAIL = 'CREATE_UPDATE_QUESTION_FAIL'

export const DELETE_QUESTION_START = 'DELETE_QUESTION_START'
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS'
export const DELETE_QUESTION_FAIL = 'DELETE_QUESTION_FAIL'

export const SET_TEST_FORM_SECTION = 'SET_TEST_FORM_SECTION'

// export const INSTRUCTOR_LOADING = 'INSTRUCTOR_LOADING'

export const MODULES_CHANGE_START = 'MODULES_CHANGE_START'
export const MODULES_CHANGE_SUCCESS = 'MODULES_CHANGE_SUCCESS'
export const MODULES_CHANGE_FAILED = 'MODULES_CHANGE_FAILED'

export const FETCH_MODULES_START = 'FETCH_MODULES_START'
export const FETCH_MODULES_SUCCESS = 'FETCH_MODULES_SUCCESS'
export const FETCH_MODULES_FAIL = 'FETCH_MODULES_FAIL'

export const CLEAR_INSTRUCTOR_NOTIFICATION = 'CLEAR_INSTRUCTOR_NOTIFICATION'

//Student exports

export const MARK_SLIDE_AS_SEEN_START = 'MARK_SLIDE_AS_SEEN_START'
export const MARK_SLIDE_AS_SEEN_SUCCESS = 'MARK_SLIDE_AS_SEEN_SUCCESS'
export const MARK_SLIDE_AS_SEEN_FAIL = 'MARK_SLIDE_AS_SEEN_FAIL'


export const SHOW_STUDENT_COURSE_DETAILS = 'SHOW_STUDENT_COURSE_DETAILS'
export const CONFIRMING_ENROLLMENT = 'CONFIRMING_ENROLLMENT'
export const CONFIRMING_DROP_COURSE = 'CONFIRMING_DROP_COURSE'
export const SHOW_STUDENT_COURSE_SYLLABUS = 'SHOW_STUDENT_COURSE_SYLLABUS'
export const SHOW_TEST_REVIEW = 'SHOW_TEST_REVIEW'

export const SELECT_COURSE = 'SELECT_COURSE'

export const START_TEST_CONFIRMING = 'START_TEST_CONFIRMING'
export const START_TEST = 'START_TEST'
export const START_ASSIGNMENT = 'START_ASSIGNMENT'

export const SELECT_STUDENT_LESSON = 'SELECT_STUDENT_LESSON'

export const TEST_MATERIALS_STUDENT_TEST = 'TEST_MATERIALS_STUDENT_TEST'
export const MC_SECTION_STUDENT_TEST = 'MC_SECTION_STUDENT_TEST'
export const ESSAY_SECTION_STUDENT_TEST = 'ESSAY_SECTION_STUDENT_TEST'
export const FILLBLANK_SECTION_STUDENT_TEST = 'FILLBLANK_SECTION_STUDENT_TEST'
export const SPEAKING_SECTION_STUDENT_TEST = 'SPEAKING_SECTION_STUDENT_TEST'

export const FETCH_TEST_RESULTS = 'FETCH_TEST_RESULTS'
// export const STUDENT_TEST_SUBMITTED = 'STUDENT_TEST_SUBMITTED'
// export const STUDENT_ASSIGNMENT_SUBMITTED = 'STUDENT_ASSIGNMENT_SUBMITTED'
export const STUDENT_TEST_SAVED = 'STUDENT_TEST_SAVED'
export const EXIT_ASSIGNMENT = 'EXIT_ASSIGNMENT'
export const CLEAR_TEST_IN_PROGRESS = 'CLEAR_TEST_IN_PROGRESS'
export const CLEAR_STUDENT_MODAL_STATES = 'CLEAR_STUDENT_MODAL_STATES'

export const SET_INITIAL_TEST_FORM_VALUES = 'SET_INITIAL_TEST_FORM_VALUES'

export const SET_INITIAL_GRADE_VALUES = 'SET_INITIAL_GRADE_VALUES'

export const SET_INCOMPLETE_ASSIGNMENTS_REFERENCES = 'SET_INCOMPLETE_ASSIGNMENTS_REFERENCES'

export const LOAD_TEST_IN_PROGRESS = 'LOAD_TEST_IN_PROGRESS'

export const SET_STUDENT_TAB = 'SET_STUDENT_TAB'

export const SUBMIT_TEST_START = 'SUBMIT_TEST_START'
export const SUBMIT_TEST_SUCCESS = 'SUBMIT_TEST_SUCCESS'
export const SUBMIT_TEST_FAIL = 'SUBMIT_TEST_FAIL'

export const FETCH_TEST_START = 'FETCH_TEST_START'
export const FETCH_TEST_SUCCESS = 'FETCH_TEST_SUCCESS'
export const FETCH_TEST_FAIL = 'FETCH_TEST_FAIL'

export const CLOSE_TEST_START = 'CLOSE_TEST_START'
export const CLOSE_TEST_SUCCESS = 'CLOSE_TEST_SUCCESS'
export const CLOSE_TEST_FAIL = 'CLOSE_TEST_FAIL'

export const FETCH_TEST_RESULTS_START = 'FETCH_TEST_RESULTS_START'
export const FETCH_TEST_RESULTS_SUCCESS = 'FETCH_TEST_RESULTS_SUCCESS'
export const FETCH_TEST_RESULTS_FAIL = 'FETCH_TEST_RESULTS_FAIL'

export const ENROLL_COURSE_START = 'ENROLL_COURSE_START'
export const ENROLL_COURSE_SUCCESS = 'ENROLL_COURSE_SUCCESS'
export const ENROLL_COURSE_FAIL = 'ENROLL_COURSE_FAIL'

export const ENROLL_REQUEST_START = 'ENROLL_REQUEST_START'
export const ENROLL_REQUEST_SUCCESS = 'ENROLL_REQUEST_SUCCESS'
export const ENROLL_REQUEST_FAIL = 'ENROLL_REQUEST_FAIL'

export const ENROLL_DENY_START = 'ENROLL_DENY_START'
export const ENROLL_DENY_SUCCESS = 'ENROLL_DENY_SUCCESS'
export const ENROLL_DENY_FAIL = 'ENROLL_DENY_FAIL'

export const DROP_COURSE_START = 'DROP_COURSE_START'
export const DROP_COURSE_SUCCESS = 'DROP_COURSE_SUCCESS'
export const DROP_COURSE_FAIL = 'DROP_COURSE_FAIL'

export const CLEAR_STUDENT_NOTIFICATION = 'CLEAR_STUDENT_NOTIFICATION'

export const CLEAR_LOADED_INSTRUCTOR_DATA = 'CLEAR_LOADED_INSTRUCTOR_DATA'
export const CLEAR_LOADED_STUDENT_DATA = 'CLEAR_LOADED_STUDENT_DATA'

export const SET_STUDENT_TEST_SECTION = 'SET_STUDENT_TEST_SECTION'
export const SET_INSTRUCTOR_TEST_SECTION = 'SET_INSTRUCTOR_TEST_SECTION'

//Common
export const SET_WIDTH = 'SET_WIDTH'
export const SET_EDITING = 'SET_EDITING'
export const CANCEL_EDITING = 'CANCEL_EDITING'
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SET_LOADING = 'SET_LOADING'
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE'
export const SET_FAIL_MESSAGE = 'SET_FAIL_MESSAGE'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SET_CHAT_USER = 'SET_CHAT_USER'
export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const SET_TAB_LABELS = 'SET_TAB_LABELS'
export const SET_TAB = 'SET_TAB'
export const SET_COURSE = 'SET_COURSE'
export const SET_POPULATED_COURSE = 'SET_POPULATED_COURSE'
export const SET_COURSES = 'SET_COURSES'
export const SET_COURSE_PANEL = 'SET_COURSE_PANEL'


export const FETCH_COURSES_START = 'FETCH_COURSES_START'
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS'
export const FETCH_COURSES_FAIL = 'FETCH_COURSES_FAIL'

export const FETCH_NOTIFICATIONS_START = 'FETCH_NOTIFICATIONS_START'
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS'
export const FETCH_NOTIFICATIONS_FAIL = 'FETCH_NOTIFICATIONS_FAIL'

export const MARK_AS_SEEN_START = 'MARK_AS_SEEN_START'
export const MARK_AS_SEEN_SUCCESS = 'MARK_AS_SEEN_SUCCESS'
export const MARK_AS_SEEN_FAIL = 'MARK_AS_SEEN_FAIL'

export const UPLOAD_FILE_START = 'UPLOAD_FILE_START'
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_FAIL = 'UPLOAD_FILE_FAIL'

export const DELETE_FILES_START = 'DELETE_FILES_START'
export const DELETE_FILES_SUCCESS = 'DELETE_FILES_SUCCESS'
export const DELETE_FILES_FAIL = 'DELETE_FILES_FAIL'

export const INITIALIZE_SOCKET_CHANNEL = 'INITIALIZE_SOCKET_CHANNEL'
export const SOCKET_MESSAGE_RECEIVED = 'SOCKET_MESSAGE_RECEIVED'

export const ACCOUNT_VERIFICATION_START = 'ACCOUNT_VERIFICATION_START'
export const ACCOUNT_VERIFICATION_SUCCESS = 'ACCOUNT_VERIFICATION_SUCCESS'
export const ACCOUNT_VERIFICATION_FAIL = 'ACCOUNT_VERIFICATION_FAIL'

export const RESEND_EMAIL_VERIFICATION_START = 'RESEND_EMAIL_VERIFICATION_START'
export const RESEND_EMAIL_VERIFICATION_SUCCESS = 'RESEND_EMAIL_VERIFICATION_SUCCESS'
export const RESEND_EMAIL_VERIFICATION_FAIL = 'RESEND_EMAIL_VERIFICATION_FAIL'

export const REFRESH_TOKEN_START = 'REFRESH_TOKEN_START'
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL'

export const SET_SESSION_ALERT = 'SET_SESSION_ALERT'

export const SET_MIC = 'SET_MIC'

export const SET_THEME = 'SET_THEME'

//admin actions
export const SUSPEND_ACCOUNT_START = 'SUSPEND_ACCOUNT_START'
export const SUSPEND_ACCOUNT_SUCCESS = 'SUSPEND_ACCOUNT_SUCCESS'
export const SUSPEND_ACCOUNT_FAIL = 'SUSPEND_ACCOUNT_FAIL'

export const ACTIVATE_ACCOUNT_START = 'ACTIVATE_ACCOUNT_START'
export const ACTIVATE_ACCOUNT_SUCCESS = 'ACTIVATE_ACCOUNT_SUCCESS'
export const ACTIVATE_ACCOUNT_FAIL = 'ACTIVATE_ACCOUNT_FAIL'

export const REQUEST_BITCOIN_ADDRESS_START = 'REQUEST_BITCOIN_ADDRESS_START'
export const REQUEST_BITCOIN_ADDRESS_SUCCESS = 'REQUEST_BITCOIN_ADDRESS_SUCCESS'
export const REQUEST_BITCOIN_ADDRESS_FAIL = 'REQUEST_BITCOIN_ADDRESS_FAIL'

export const INTENT_CREDITCARD_PAYMENT_START = 'INTENT_CREDITCARD_PAYMENT_START'
export const INTENT_CREDITCARD_PAYMENT_SUCCESS = 'INTENT_CREDITCARD_PAYMENT_SUCCESS'
export const INTENT_CREDITCARD_PAYMENT_FAIL = 'INTENT_CREDITCARD_PAYMENT_FAIL'

export const FETCH_TRANSACTIONS_START = 'FETCH_TRANSACTIONS_START'
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS'
export const FETCH_TRANSACTIONS_FAIL = 'FETCH_TRANSACTIONS_FAIL'

export const FETCH_CRYPTO_CHARGES_START = 'FETCH_CRYPTO_CHARGES_START'
export const FETCH_CRYPTO_CHARGES_SUCCESS = 'FETCH_CRYPTO_CHARGES_SUCCESS'
export const FETCH_CRYPTO_CHARGES_FAIL = 'FETCH_CRYPTO_CHARGES_FAIL'